version: '3.8'

services:
  # ==========================================
  # 1. MICROSERVICIOS REALES (SPRING BOOT)
  # ==========================================
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    restart: always

  producto-service:
    build: ./producto-service
    container_name: producto-service
    ports:
      - "8082:8082"
    restart: always

  usuario-service:
    build: ./usuario-service
    container_name: usuario-service
    ports:
      - "8083:8083"
    restart: always

  # ==========================================
  # 2. CONTENEDORES DE CONTINGENCIA (ESPACIO 0)
  # ==========================================
  carrito-service:
    image: alpine
    container_name: carrito-service
    command: tail -f /dev/null
    ports:
      - "8084:8084"
    restart: always

  catalogo-service:
    image: alpine
    container_name: catalogo-service
    command: tail -f /dev/null
    ports:
      - "8085:8085"
    restart: always

  inventario-service:
    image: alpine
    container_name: inventario-service
    command: tail -f /dev/null
    ports:
      - "8086:8086"
    restart: always

  pago-service:
    image: alpine
    container_name: pago-service
    command: tail -f /dev/null
    ports:
      - "8087:8087"
    restart: always

  envio-service:
    image: alpine
    container_name: envio-service
    command: tail -f /dev/null
    ports:
      - "8088:8088"
    restart: always

  notificacion-service:
    image: alpine
    container_name: notificacion-service
    command: tail -f /dev/null
    ports:
      - "8089:8089"
    restart: always

  reportes-service:
    image: alpine
    container_name: reportes-service
    command: tail -f /dev/null
    ports:
      - "8090:8090"
    restart: always
