spring.application.name=usuario-service
server.port=8083

# Configuración de la base de datos (Usa el contenedor db-usuarios)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://db-usuarios:3306/usuarios_db}
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Crear las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
