spring.application.name=usuario-service
# Puerto del microservicio
server.port=8081

# Nombre de la aplicación
spring.application.name=usuario-service

# Configuración de conexión a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/usuariodb?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=tu_password

# Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
